version: '3'

services:
  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    profiles:
      - watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: ${WT_POLL_INTERVAL:-86400}
      WATCHTOWER_SCOPE: ${WT_SCOPE}
      WATCHTOWER_NOTIFICATION_URL: smtp://${SMTP_USERNAME}:${SMTP_PASSWORD}@${SMTP_HOST}:${SMTP_PORT}/?from=${SMTP_FROM}&to=${WT_NOTIFY_EMAIL}
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: ${WT_HOSTNAME}
      WATCHTOWER_MONITOR_ONLY: ${WT_MONITOR_ONLY:-false}
      WATCHTOWER_NO_STARTUP_MESSAGE: ${WT_NO_STARTUP_MESSAGE:-false}
    labels:
      - "com.centurylinklabs.watchtower.scope=${WT_SCOPE}"

  portainer:
    image: portainer/agent:latest
    restart: unless-stopped
    profiles:
      - portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    labels:
      - "com.centurylinklabs.watchtower.scope=${WT_SCOPE}"

