include:
  - path: ../common/watchtower/compose.yaml
  - path: ../common/acme/compose.yaml

services:
  adguard:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    hostname: adguard.${HOSTNAME:?Set the HOSTNAME .env variable}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "784:784/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
      - acme_certs:/opt/ssl
    labels:
      - sh.acme.autoload.domain=dns
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}
  
  unbound:
    image: madnuttah/unbound:latest
    restart: unless-stopped
    hostname: unbound.${HOSTNAME:?Set the HOSTNAME .env variable}
    volumes:
      - ./unbound.conf:/usr/local/unbound/unbound.conf:rw
    volumes_from:
      - redis-socket:rw
    depends_on:
      - redis
    labels:
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: '--dir /usr/local/unbound/cachedb.d --unixsocket /usr/local/unbound/cachedb.d/redis.sock --unixsocketperm 777 --appendonly yes --appendfsync everysec'
    volumes_from:
      - redis-socket:rw
    labels:
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}

  redis-socket:
    image: busybox
    container_name: redis-socket
    command: install -d -m 0755 -o 999 -g 1000 /usr/local/unbound/cachedb.d
    volumes:
      - cachedb:/usr/local/unbound/cachedb.d

  metrics-exporter:
    image: ghcr.io/henrywhitaker3/adguard-exporter:latest
    restart: unless-stopped
    hostname: metrics-exporter.${HOSTNAME:?Set the HOSTNAME .env variable}
    ports:
      - "9618:9618"
    environment:
      - ADGUARD_SERVERS=https://dns.zuba.dev
      - ADGUARD_USERNAMES=administrator
      - ADGUARD_PASSWORDS=${ADGUARD_PASSWORDS}
      - INTERVAL=15s
    
volumes:
  adguard_work:
  adguard_conf:
  cachedb:
