version: "3"

include:
  - path: ../common/watchtower/compose.yaml
  - path: ../common/portainer/compose.yaml
  - path: ../common/acme/compose.yaml

services:
  adguard:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    hostname: adguard.${HOSTNAME:?Set the HOSTNAME .env variable}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "853:853/udp"
      - "784:784/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
      - acme_certs:/opt/ssl
    labels:
      - sh.acme.autoload.domain=dns
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}

  kresd:
    image: cznic/knot-resolver:6
    restart: unless-stopped
    hostname: kresd.${HOSTNAME:?Set the HOSTNAME .env variable}
    volumes:
      - kresd_cache:/var/cache/knot-resolver
      - ./kresd.yaml:/config/config.yaml
    labels:
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}

volumes:
  adguard_work:
  adguard_conf:
  kresd_cache:
