version: "3"

include:
  - path: ../common/portainer/compose.yaml
  - path: ../common/watchtower/compose.yaml

services:
  influx:
    image: influxdb:2.7-alpine
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb2
      - influx_config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUX_USERNAME:?Influx Init Username is required}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUX_PASSWORD:?Influx Init Password is required}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUX_ORG:?Influx Init Org is required}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUX_BUCKET:?Influx Init Bucket is required}
    labels:
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}

volumes:
  influx_data:
  influx_config:
