services:
  watchtower:
    image: nickfedor/watchtower:latest
    restart: unless-stopped
    env_file: .env
    hostname: watchtower.${HOSTNAME:?Set the HOSTNAME .env variable}
    healthcheck:
      disable: true
    environment:
      WATCHTOWER_SCOPE: ${HOSTNAME}
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: ${HOSTNAME}
      WATCHTOWER_UPDATE_ON_START: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}
