version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    profiles:
      - vaultwarden
    networks:
      vaultwarden:
    restart: unless-stopped
    environment:
      DOMAIN: ${VW_DOMAIN}
      SIGNUPS_ALLOWED: ${VW_SIGNUPS_ALLOWED:-false}
      INVITATIONS_ALLOWED: ${VW_INVITATIONS_ALLOWED:-true}
      ADMIN_TOKEN: ${VW_ADMIN_TOKEN}
      ROCKET_LIMITS: ${VW_ROCKET_LIMITS:-{json=10485760}}
      ROCKET_WORKERS: ${VW_ROCKET_WORKERS:-10}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_SECURITY: ${VW_SMTP_SECURITY:-starttls}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SHOW_PASSWORD_HINT: ${VW_SHOW_PASSWORD_HINT:-true}
      EXTENDED_LOGGING: ${VW_EXTENDED_LOGGING:-false}
      LOG_LEVEL: ${VW_LOG_LEVEL:-info}
      IP_HEADER: X-Forwarded-For
    volumes:
      - vw_data:/data
    labels:
      - "com.centurylinklabs.watchtower.scope=vaultwarden"

  cloudflared-tunnel: &cloudflared
    image: cloudflare/cloudflared:latest
    profiles:
      - vaultwarden
    networks:
      vaultwarden:
    restart: unless-stopped
    command: tunnel run
    volumes:
      - cloudflared_data:/home/nonroot/.cloudflared
      - type: bind
        source: ./cloudflared.yml
        target: /home/nonroot/.cloudflared/config.yml
    labels:
      - "com.centurylinklabs.watchtower.scope=vaultwarden"

  cloudflared-login:
    <<: *cloudflared
    restart: never
    profiles:
      - donotrun
    command: tunnel login
    depends_on:
      cloudflared-vol-ownership:
        condition: service_completed_successfully

  cloudflared-create:
    <<: *cloudflared
    restart: no
    profiles:
      - donotrun
    command: tunnel create ${CF_TUNNEL_NAME}

  cloudflared-route:
    <<: *cloudflared
    restart: no
    profiles:
      - donotrun
    command: tunnel route dns --overwrite-dns ${CF_TUNNEL_NAME} ${CF_TUNNEL_HOST}

  cloudflared-delete:
    <<: *cloudflared
    restart: no
    profiles:
      - donotrun
    command: tunnel delete ${CF_TUNNEL_NAME}

  # Thanks Docker!
  # https://pratikpc.medium.com/use-docker-compose-named-volumes-as-non-root-within-your-containers-1911eb30f731
  cloudflared-vol-ownership:
    image: busybox:latest
    networks:
      vaultwarden:
    profiles:
      - donotrun
    volumes:
      - cloudflared_data:/home/nonroot/.cloudflared
    command: chown -vcR 65532:65532 /home/nonroot/.cloudflared

volumes:
  vw_data:
  cloudflared_data:

networks:
  vaultwarden:
