version: "3"

include:
  - path: ../common/watchtower/compose.yaml
  - path: ../common/portainer/compose.yaml
  - path: ../common/acme/compose.yaml
  - path: ../common/promtail/compose.yaml

services:
  speedtest:
    image: openspeedtest/latest:latest
    restart: unless-stopped
    hostname: speedtest.${HOSTNAME:?Set the HOSTNAME .env variable}
    ports:
      - "443:3001"
    labels:
      - sh.acme.autoload.domain=speed
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}
      - com.grafana.promtail=true

  iperf3:
    image: networkstatic/iperf3:latest
    command: -s
    restart: unless-stopped
    hostname: iperf3.${HOSTNAME:?Set the HOSTNAME .env variable}
    ports:
      - "5201:5201/udp"
      - "5201:5201/tcp"
    labels:
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}
      - com.grafana.promtail=true

networks:
  default:
    name: speedtest
