version: "3"

include:
  - path: ../common/watchtower/compose.yaml
  - path: ../common/portainer/compose.yaml
  - path: ../common/acme/compose.yaml

services:
  speedtest:
    image: openspeedtest/latest:latest
    restart: unless-stopped
    ports:
      - "8443:3001"
    labels:
      - sh.acme.autoload.domain=speed
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}

  iperf3:
    image: networkstatic/iperf3:latest
    restart: unless-stopped
    ports:
      - "5201:5201/udp"
      - "5201:5201/tcp"
    labels:
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}
    command: -s

networks:
  default:
    name: speedtest
