include:
  - path: ../common/watchtower/compose.yaml

services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    hostname: grafana.${HOSTNAME:?Set the HOSTNAME .env variable}
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SERVER_DOMAIN=${HOSTNAME}
      - GF_SERVER_ROOT_URL=https://${HOSTNAME}
      - GF_SERVER_CERT_KEY=/opt/ssl/grafana.key
      - GF_SERVER_CERT_FILE=/opt/ssl/grafana.crt
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_ENFORCE_DOMAIN=false
    ports:
      - "443:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
      - acme_certs:/opt/ssl
      - ./prom_ds.yaml:/etc/grafana/provisioning/datasources/prom_ds.yaml
    labels:
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}
      - sh.acme.autoload.domain=grafana

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    hostname: prometheus.${HOSTNAME:?Set the HOSTNAME .env variable}
    command: '--config.file=/etc/prometheus/prometheus.yaml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=365d'
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    labels:
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}

  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    restart: unless-stopped
    hostname: unpoller.${HOSTNAME:?Set the HOSTNAME .env variable}
    environment:
      - UP_INFLUXDB_DISABLE=true
      - UP_UNIFI_DEFAULT_URL=https://10.0.2.1
    labels:
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}

  # Thanks Docker!
  # https://pratikpc.medium.com/use-docker-compose-named-volumes-as-non-root-within-your-containers-1911eb30f731
  grafana-ssl-vol-ownership:
    image: busybox:latest
    profiles:
      - do-not-run
    volumes:
      - acme_certs:/opt/ssl
    command: chown -vcR 472:0 /opt/ssl
    
volumes:
  acme_certs:
  grafana_storage:
  prometheus_data:
