version: "3"

include:
  - path: ../common/acme.sh/compose.yaml
  - path: ../common/portainer/compose.yaml
  - path: ../common/watchtower/compose.yaml

services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
      - ./loki_ds.yaml:/etc/grafana/provisioning/datasources/loki_ds.yaml
    labels:
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}

  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml -reporting.enabled=false
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    labels:
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}
      - com.grafana.promtail=true

  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail.yaml -config.expand-env=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail.yaml:/etc/promtail/promtail.yaml
    labels:
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}

  syslog:
    image: balabit/syslog-ng:latest
    restart: unless-stopped
    ports:
      - "514:514/udp"
      - "514:514/tcp"
      - "601:601/tcp"
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
    labels:
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}

volumes:
  grafana_storage:
  loki_data:
