server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://${LOKI_URL:-loki}:3100/loki/api/v1/push

scrape_configs:
  - job_name: syslog
    syslog:
      listen_address: 0.0.0.0:601
      labels:
        job: syslog
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: host
      - source_labels: ['__syslog_message_severity']
        target_label: level
      - source_labels: ['__syslog_message_app_name']
        target_label: application
      - source_labels: ['__syslog_message_facility']
        target_label: facility
      - source_labels: ['__syslog_connection_hostname']
        target_label: connection_hostname
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: [com.grafana.promtail=true]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: logstream
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: job
  - job_name: gelf
    gelf:
      listen_address: 0.0.0.0:12201
      labels:
        job: gelf
    pipeline_stages:
      - match:
          selector: '{job="gelf"}'
          stages:
            - json:
                expressions:
                  container: _container_name
                  message: short_message
            - labels:
                container:
            - output:
                source: message
    relabel_configs:
      - source_labels: ['__gelf_message_level']
        target_label: level
      - source_labels: ['__gelf_message_host']
        target_label: host
      - source_labels: ['__gelf_message_facility']
        target_label: facility

