global:
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
    - OpenMetricsText1.0.0
    - OpenMetricsText0.0.1
    - PrometheusText1.0.0
    - PrometheusText0.0.4
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: unpoller
    static_configs:
      - targets:
          - unpoller:9130
        labels: 
          instance: unifi.zuba.dev  
  - job_name: dns_discovery
    dns_sd_configs: 
      - names:
          - _prometheus._tcp.zuba.dev
    relabel_configs: 
      - source_labels: [__meta_dns_srv_record_target]
        target_label: instance
        regex: (.*)\.$
        replacement: $1
        