version: '3'

services:
  acme:
    image: neilpang/acme.sh:latest
    restart: unless-stopped
    command: daemon
    env_file: .env
    hostname: acme.${HOSTNAME:?Set the HOSTNAME .env variable}
    volumes:
      - acme_data:/acme.sh
      - acme_certs:/opt/ssl
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}

volumes:
  acme_data:
  acme_certs:
