version: "3"

services:
  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail.yaml -config.expand-env=true
    env_file: .env
    hostname: promtail.${HOSTNAME:?Set the HOSTNAME .env variable}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail.yaml:/etc/promtail/promtail.yaml
    labels:
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}
