include:
  - path: ../common/watchtower/compose.yaml

services:
  xo:
    image: ezka77/xen-orchestra-ce:latest
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    healthcheck:
      disable: true
    environment:
      - XO_HTTP_LISTEN_PORT=80
      - XO_HTTPS_LISTEN_PORT=443
      - XO_HTTP_REDIRECTTOHTTPS=true
      - XO_HTTPS_LISTEN_CERT=/opt/ssl/ssl.crt
      - XO_HTTPS_LISTEN_KEY=/opt/ssl/ssl.key
      - DEBUG=xo:main
      - NODE_ENV=production
      - XOA_PLAN=5
    cap_add:
      - SYS_ADMIN
    # LVM 
    devices:
      - "/dev/fuse:/dev/fuse"
      - "/dev/loop-control:/dev/loop-control"
    volumes:
      - xo_data:/storage
      - acme_certs:/opt/ssl
    labels:
      - sh.acme.autoload.domain=xo
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: '--appendonly yes --appendfsync everysec'
    volumes:
      - redis_data:/data
    labels:
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}

volumes:
  xo_data:
  redis_data:
  acme_certs:
