mqtt:
  host: mqtt.ha.zuba.dev
  username: !secret mqtt_username
  password: !secret mqtt_password

ui:
  path: /double-take

frigate:
  url: http://frigate:5000
  update_sub_labels: true

detectors:
  aiserver:
    url: http://codeproject:32168

detect:
  match:
    min_area: 1000

telemetry: false
