mqtt:
  host: mqtt.ha.zuba.dev
  user: "{FRIGATE_MQTT_USER}"
  password: "{FRIGATE_MQTT_PASSWORD}"

record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: true
  bounding_box: false
  crop: true
  timestamp: false
  retain:
    default: 10
    mode: all

objects:
  # Optional: list of objects to track from labelmap.txt (default: shown below)
  track:
    - person

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h264

go2rtc:
  streams:
    garage-east:
      - rtsp://{FRIGATE_REOLINK_RTSP_USERNAME}:{FRIGATE_REOLINK_RTSP_PASSWORD}@10.0.30.10/h264Preview_01_main
    garage-east-sub:
      - rtsp://{FRIGATE_REOLINK_RTSP_USERNAME}:{FRIGATE_REOLINK_RTSP_PASSWORD}@10.0.30.10/h264Preview_01_sub
    doorbell:
      - rtsp://{FRIGATE_TAPO_RTSP_USERNAME}:{FRIGATE_TAPO_RTSP_PASSWORD}@doorbell-camera.zuba.dev/stream1
    doorbell-sub:
      - rtsp://{FRIGATE_TAPO_RTSP_USERNAME}:{FRIGATE_TAPO_RTSP_PASSWORD}@doorbell-camera.zuba.dev/stream2
    patio:
      - rtsp://{FRIGATE_TAPO_RTSP_USERNAME}:{FRIGATE_TAPO_RTSP_PASSWORD}@patio-camera.zuba.dev/stream1
    patio-sub:
      - rtsp://{FRIGATE_TAPO_RTSP_USERNAME}:{FRIGATE_TAPO_RTSP_PASSWORD}@patio-camera.zuba.dev/stream2
  webrtc:
    candidates:
      - 10.0.30.212:8555
      - stun:8555

cameras:
  garage-east:
    objects:
      track:
        - car
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage-east
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/garage-east-sub
          roles:
            - audio
            - detect
    detect:
      enabled: False

  doorbell:
    motion:
      mask:
        - 2286,1547,1890,1379,1420,899,982,893,948,0,2034,0
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/doorbell
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/doorbell-sub
          roles:
            - detect
            - audio
    detect:
      enabled: True

  patio:
    objects:
      track:
        - person
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/patio
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/patio-sub
          roles:
            - detect
            - audio
    detect:
      enabled: True
