version: '3'

services:
  portainer:
    image: portainer/agent:latest
    restart: unless-stopped
    hostname: portainer.${HOSTNAME:?Set the HOSTNAME .env variable}
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    labels:
      - com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}
