version: '3'

services:
  portainer:
    image: portainer/agent:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
    labels:
      - "com.centurylinklabs.watchtower.scope=${WATCHTOWER_SCOPE}"
