include:
  - path: ../common/watchtower/compose.yaml

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - rustdesk-data:/root
    network_mode: "host"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - rustdesk-data:/root
    network_mode: "host"
    restart: unless-stopped

volumes:
  rustdesk-data: