include:
  - path: ../common/watchtower/compose.yaml
  - path: ../common/cloudflare/compose.yaml

services:
  ollama:
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    labels:
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    volumes:
      - open-webui-data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-8080}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.scope=${HOSTNAME}

volumes:
  ollama-data: {}
  open-webui-data: {}